const mongoose=require('mongoose');
const S=new mongoose.Schema({
  seller:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true},
  sellerName:{type:String},
  sellerEmail:{type:String},
  title:{type:String,required:true},
  year:{type:String,required:true},
  make:{type:String,required:true},
  model:{type:String,required:true},
  trim:{type:String},
  mileage:{type:Number,required:true},
  price:{type:Number,required:true},
  titleStatus:{type:String,default:'Clean Title'},
  condition:{type:String,default:'Good'},
  color:{type:String},
  transmission:{type:String,default:'Automatic'},
  drivetrain:{type:String,default:'FWD'},
  engine:{type:String},
  description:{type:String,required:true},
  knownProblems:{type:String},
  phone:{type:String},
  city:{type:String,required:true},
  state:{type:String,required:true},
  images:[{type:String}],
  status:{type:String,default:'active'},
  views:{type:Number,default:0},
  createdAt:{type:Date,default:Date.now},
});
module.exports=mongoose.model('Listing',S);
