require('dotenv').config({path:require('path').join(__dirname,'../.env')});
const express=require('express');
const cors=require('cors');
const path=require('path');
const connectDB=require('./config/db');
const app=express();
connectDB();
app.use(cors({origin:['http://localhost:3000','http://localhost:3001','https://mechaapp.vercel.app','https://mechatech.io','https://www.mechatech.io'],credentials:true}));
app.use(express.json({limit:'10mb'}));
app.use(express.urlencoded({extended:true}));
app.use('/uploads',express.static(path.join(__dirname,'../uploads')));
app.use('/api/auth',require('./routes/auth'));
app.use('/api/vehicles',require('./routes/vehicles'));
app.use('/api/diagnoses',require('./routes/diagnoses'));
app.use('/api/shops',require('./routes/shops'));
app.use('/api/towing',require('./routes/towing'));
app.use('/api/listings',require('./routes/listings'));
app.use('/api/payments',require('./routes/payments'));
app.get('/api/health',(_,res)=>res.json({status:'online',db:require('mongoose').connection.readyState===1?'connected':'disconnected'}));
const PORT=process.env.PORT||5000;
app.listen(PORT,()=>{
  console.log('');
  console.log('\x1b[31m  ███╗   ███╗███████╗ ██████╗██╗  ██╗ █████╗ \x1b[0m');
  console.log('\x1b[31m  ██╔████╔██║█████╗  ██║     ███████║███████║\x1b[0m');
  console.log('\x1b[31m  ██║ ╚═╝ ██║███████╗╚██████╗██║  ██║██║  ██║\x1b[0m');
  console.log('');
  console.log(`\x1b[32m  ✅  Server → http://localhost:${PORT}\x1b[0m`);
  console.log(`\x1b[33m  ⚠️   Edit backend/.env — add your MONGO_URI!\x1b[0m`);
  console.log('');
});
