import axios from'axios';
const api=axios.create({baseURL:process.env.REACT_APP_API_URL||'http://localhost:5000',withCredentials:true});
api.interceptors.request.use(c=>{const t=localStorage.getItem('mechaToken');if(t)c.headers.Authorization=`Bearer ${t}`;return c;});
api.interceptors.response.use(r=>r,e=>{if(e.response?.status===401){localStorage.clear();window.location.href='/';}return Promise.reject(e);});
export const registerDriver=d=>api.post('/api/auth/register',d);
export const loginDriver=d=>api.post('/api/auth/login',d);
export const googleVerify=c=>api.post('/api/auth/google/verify',{credential:c});
export const getVehicles=()=>api.get('/api/vehicles');
export const addVehicle=d=>api.post('/api/vehicles',d);
export const deleteVehicle=id=>api.delete(`/api/vehicles/${id}`);
export const saveDiagnosis=d=>api.post('/api/diagnoses',d);
export const registerShop=d=>api.post('/api/shops/register',d);
export const loginShop=d=>api.post('/api/shops/login',d);
export const googleShop=c=>api.post('/api/shops/google/verify',{credential:c});
export const getNearbyShops=(lat,lng,r)=>api.get(`/api/shops/nearby?lat=${lat}&lng=${lng}&radius=${r||25}`);
export const getShopsByZip=z=>api.get(`/api/shops/zip/${z}`);
export const contactShop=(id,body)=>api.post('/api/shops/contact',{shopId:id,body});
export const registerTowing=d=>api.post('/api/towing/register',d);
export const loginTowing=d=>api.post('/api/towing/login',d);
export const googleTowing=c=>api.post('/api/towing/google/verify',{credential:c});
export default api;

export const createCheckout = (plan) => api.post('/payments/create-checkout', {plan});
